language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3
install:
  - pip install flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; else pip install coverage; fi
  - pip install coveralls
  - pip install mock
  - pip install nose
  - pip install requests
  - pip install responses
script:
  - nosetests tests --with-coverage --cover-package=retdec --cover-erase
  - flake8 --ignore=E501 retdec tests
after_success:
  - coveralls
